<?php
// config/idiomas.php

$textos = [
    'es' => [
        // --- Página de Inicio ---
        'titulo_app' => 'NoDou - Cuentas claras, amistades largas',
        'tagline' => 'Cuentas claras, amistades largas.',
        'descripcion_app' => 'La forma más elegante y sencilla de dividir gastos con amigos, familiares o compañeros de piso sin complicaciones.',
        'iniciar_sesion' => 'Iniciar Sesión',
        'registrarse' => 'Registrarse',
        'division_inteligente' => '✓ División Inteligente',
        'gastos_fijos_feature' => '✓ Gastos Fijos',
        'estadisticas_feature' => '✓ Estadísticas',
        
        // --- Menú y Navegación ---
        'inicio' => 'Inicio',
        'dashboard' => 'Panel de Control',
        'dividir' => 'Dividir',
        'gastos_fijos' => 'Gastos Fijos',
        'historial' => 'Historial',
        'contactos' => 'Contactos',
        'estadisticas' => 'Estadísticas',
        'calculos' => 'Cálculos',
        'perfil' => 'Mi Perfil',
        'cerrar_sesion' => 'Cerrar Sesión',
        'admin_panel' => 'Panel de Administración',
        'fijos' => 'Fijos',
        'admin' => 'Admin',
        'logs' => 'Registros',
        
        // --- Login y Registro ---
        'tus_cuentas_claras' => 'Tus cuentas claras, siempre.',
        'correo_electronico' => 'Correo electrónico',
        'ejemplo_correo' => 'ejemplo@correo.com',
        'contrasena' => 'Contraseña',
        'tu_contrasena' => 'Tu contraseña',
        'nombre_completo' => 'Nombre completo',
        'ej_nombre' => 'Ej. Juan Pérez',
        'entrar' => 'Entrar',
        'crea_tu_cuenta' => 'Crea tu cuenta',
        'empieza_dividir' => 'Empieza a dividir tus gastos de forma inteligente.',
        'aun_no_tienes_cuenta' => '¿Aún no tienes cuenta? Regístrate gratis',
        'volver_inicio' => '← Volver al inicio',
        'ya_tienes_cuenta' => '¿Ya tienes cuenta? Inicia sesión aquí',
        'registrarse_ahora' => 'Registrarse ahora',
        'error_credenciales' => 'Correo o contraseña incorrectos.',
        'error_email_existe' => 'Este correo ya está registrado.',
        'error_db' => 'Error de conexión.',
        'error_inesperado' => 'Ocurrió un error inesperado.',
        'registro_exitoso' => '¡Registro exitoso! Ahora inicia sesión.',
        'minimo_caracteres' => 'Mínimo 8 caracteres',
        
        // --- Dashboard ---
        'hola' => '¡Hola, ',
        'que_vamos_gestionar' => '¿Qué vamos a gestionar hoy?',
        'nueva_cuenta' => 'Nueva Cuenta',
        'divide_gasto_nuevo' => 'Divide un gasto nuevo entre varias personas.',
        'historial_gastos' => 'Historial',
        'revisa_cuentas' => 'Revisa todas las cuentas y gastos que has registrado.',
        'estadisticas' => 'Estadísticas',
        'mira_tendencias' => 'Mira tus tendencias, cuánto debes y cuánto te deben.',
        'gastos_fijos_label' => 'Gastos Fijos',
        'controla_pagos' => 'Controla tus pagos recurrentes mensuales.',
        'mis_contactos' => 'Mis Contactos',
        'gestiona_personas' => 'Gestiona tus personas frecuentes y saldos.',
        'perfil_usuario' => 'Mi Perfil',
        'ver_datos_personales' => 'Ve tus datos personales y opciones.',
        
        // --- Nueva Cuenta / Gasto ---
        'registrar_nuevo_gasto' => 'Registrar Nuevo Gasto',
        'info_gasto' => 'Información del Gasto',
        'participantes_section' => 'Participantes',
        'detalle_articulos' => 'Detalle de Artículos',
        'titulo' => 'Título',
        'que_compraste' => '¿Qué compraste?',
        'fecha' => 'Fecha',
        'metodo_division' => 'Método de División',
        'partes_iguales' => 'Por partes iguales',
        'por_porcentaje' => 'Por porcentaje (%)',
        'por_articulos' => 'Por artículos (Detallado)',
        'monto_total' => 'Monto Total ($)',
        'monto_placeholder' => '0.00',
        'calculado_automaticamente' => '🤖 Calculado automáticamente por la suma de artículos.',
        'aniade_personas' => 'Añade los ítems del ticket y selecciona quién consumió cada uno.',
        'anadir_persona' => 'Añadir Persona',
        'anadir_articulo' => 'Añadir Artículo',
        'quien_pago' => '¿Quién pagó la cuenta entera?',
        'me_deben_dinero' => 'Yo (Me deben dinero)',
        'guardar_gasto' => 'Guardar Gasto',
        'nombre_participante' => 'Nombre participante',
        'lista_contactos' => 'lista-contactos',
        
        // --- Historial de Gastos ---
        'historial_de_gastos' => 'Historial de Gastos',
        'revisa_todas' => 'Revisa todas las cuentas que has registrado y marca quién ya te pagó.',
        'genial_marcado' => '¡Genial! Se ha marcado como pagado correctamente. 🎉',
        'no_gastos_aun' => 'No tienes gastos registrados aún. ¡Ve a "Dividir" para crear uno!',
        'pagado_por' => 'Pagado por:',
        'mi_parte' => 'Mi parte',
        'estado' => 'Estado',
        'pagado' => 'Pagado ✔️',
        'pendiente' => 'Pendiente',
        'recibido' => 'Recibido ✅',
        'confirmas_que_pago' => '¿Confirmas que ',
        'ya_pago_su_parte' => ' ya pagó su parte?',
        
        // --- Estadísticas ---
        'tus_tendencias' => 'Tus Tendencias Financieras',
        'gastado_ultimo_mes' => 'Gastado el último mes',
        'por_cobrar_me_deben' => 'Por Cobrar (Me deben)',
        'por_pagar_debo' => 'Por Pagar (Debo)',
        'comparacion_mes_mes' => 'Comparación Mes a Mes',
        'gastos_por_categoria' => 'Gastos por Categoría',
        'total_gastado' => 'Total Gastado ($)',
        
        // --- Gastos Fijos ---
        'mis_gastos_fijos' => 'Mis Gastos Fijos',
        'controla_recurrentes' => 'Controla tus pagos recurrentes del mes',
        'nuevo_gasto_fijo' => 'Nuevo Gasto Fijo',
        'titulo_label' => 'Título',
        'ej_netflix' => 'Ej: Netflix, Alquiler...',
        'monto_label' => 'Monto ($)',
        'dia_cobro' => 'Día de cobro (1-31)',
        'dia_valor' => '15',
        'guardar_fijo' => 'Guardar Gasto Fijo',
        'dia_badge' => 'Día ',
        'no_gastos_fijos' => 'No tienes gastos fijos registrados.',
        'monto_fijo' => '$',
        
        // --- Contactos ---
        'mis_personas_frecuentes' => 'Mis Personas Frecuentes',
        'nombre_contacto' => 'Nombre del nuevo contacto...',
        'anadir_contacto' => 'Añadir',
        'seguro_eliminar' => '¿Seguro que deseas eliminar este contacto? Sus gastos seguirán en el historial.',
        'sigue_en_historial' => 'Sigue en el historial.',
        'me_debe' => 'Me debe',
        'le_debo' => 'Le debo',
        'cobrar' => 'Cobrar',
        'pagar' => 'Pagar',
        'sin_movimientos' => 'Sin movimientos pendientes',
        
        // --- Mensajes de Sistema ---
        'accion_irreversible' => '¿Estás seguro? Esta acción no se puede deshacer.',
        'bienvenido_vuelta' => '¡Bienvenido de nuevo, ',
        'gasto_guardado' => 'El gasto se ha guardado correctamente.',
        'contacto_guardado' => 'Contacto guardado con éxito.',
        'procesando' => 'Procesando...',
        'error' => 'Error',
        'exito' => 'Éxito',
        'total_usuarios_registrados' => 'Total de Usuarios Registrados',
        'monitor_eventos' => 'Monitor de Eventos (NoSQL JSON)',
        'lectura_json_descripcion' => 'Lectura directa desde el archivo JSON sin usar la base de datos relacional.',
        'fecha_hora' => 'Fecha y Hora',
        'id_usuario' => 'ID Usuario',
        'accion' => 'Acción',
        'detalle_dinamico' => 'Detalle Dinámico (JSON)',
        'no_registros_actividad' => 'No hay registros de actividad aún.',
        'calculos' => 'Cálculos',
        'divisor_con_propina' => 'Divisor con Propina',
        'monto_total_ticket' => 'Monto Total del Ticket',
        'de_propina' => 'de Propina',
        'entre_cuantos' => '¿Entre cuántos?',
        'cada_uno_paga' => 'Cada uno paga:',
        'detalle_propina' => '(Incluye $0.00 de propina total)',
        'notificaciones' => 'Notificaciones',
    ],
    
    'en' => [
        // --- Home Page ---
        'titulo_app' => 'NoDou - Clear Accounts, Long Friendships',
        'tagline' => 'Clear accounts, long friendships.',
        'descripcion_app' => 'The most elegant and simple way to split expenses with friends, family or roommates without complications.',
        'iniciar_sesion' => 'Log In',
        'registrarse' => 'Sign Up',
        'division_inteligente' => '✓ Smart Division',
        'gastos_fijos_feature' => '✓ Fixed Expenses',
        'estadisticas_feature' => '✓ Statistics',
        
        // --- Menu & Navigation ---
        'inicio' => 'Home',
        'dashboard' => 'Dashboard',
        'dividir' => 'Split',
        'gastos_fijos' => 'Fixed Expenses',
        'historial' => 'History',
        'contactos' => 'Contacts',
        'estadisticas' => 'Statistics',
        'calculos' => 'Calculations',
        'perfil' => 'My Profile',
        'cerrar_sesion' => 'Log Out',
        'admin_panel' => 'Admin Panel',
        'fijos' => 'Fixed',
        'admin' => 'Admin',
        'logs' => 'Logs',
        
        // --- Login & Registration ---
        'tus_cuentas_claras' => 'Your clear accounts, always.',
        'correo_electronico' => 'Email address',
        'ejemplo_correo' => 'example@email.com',
        'contrasena' => 'Password',
        'tu_contrasena' => 'Your password',
        'nombre_completo' => 'Full name',
        'ej_nombre' => 'E.g. John Smith',
        'entrar' => 'Log In',
        'crea_tu_cuenta' => 'Create your account',
        'empieza_dividir' => 'Start splitting your expenses intelligently.',
        'aun_no_tienes_cuenta' => 'Don\'t have an account yet? Sign up for free',
        'volver_inicio' => '← Back to home',
        'ya_tienes_cuenta' => 'Already have an account? Log in here',
        'registrarse_ahora' => 'Sign up now',
        'error_credenciales' => 'Incorrect email or password.',
        'error_email_existe' => 'This email is already registered.',
        'error_db' => 'Connection error.',
        'error_inesperado' => 'An unexpected error occurred.',
        'registro_exitoso' => 'Registration successful! Now log in.',
        'minimo_caracteres' => 'Minimum 8 characters',
        
        // --- Dashboard ---
        'hola' => 'Hi, ',
        'que_vamos_gestionar' => 'What are we managing today?',
        'nueva_cuenta' => 'New Expense',
        'divide_gasto_nuevo' => 'Split a new expense among several people.',
        'historial_gastos' => 'History',
        'revisa_cuentas' => 'Review all your accounts and expenses.',
        'estadisticas' => 'Statistics',
        'mira_tendencias' => 'See your trends, how much you owe and are owed.',
        'gastos_fijos_label' => 'Fixed Expenses',
        'controla_pagos' => 'Control your monthly recurring payments.',
        'mis_contactos' => 'My Contacts',
        'gestiona_personas' => 'Manage your frequent people and balances.',
        'perfil_usuario' => 'My Profile',
        'ver_datos_personales' => 'View your personal data and options.',
        
        // --- New Expense ---
        'registrar_nuevo_gasto' => 'Register New Expense',
        'info_gasto' => 'Expense Information',
        'participantes_section' => 'Participants',
        'detalle_articulos' => 'Item Details',
        'titulo' => 'Title',
        'que_compraste' => 'What did you buy?',
        'fecha' => 'Date',
        'metodo_division' => 'Split Method',
        'partes_iguales' => 'Equal parts',
        'por_porcentaje' => 'By percentage (%)',
        'por_articulos' => 'By items (Detailed)',
        'monto_total' => 'Total Amount ($)',
        'monto_placeholder' => '0.00',
        'calculado_automaticamente' => '🤖 Automatically calculated from the sum of items.',
        'aniade_personas' => 'Add the ticket items and select who consumed each one.',
        'anadir_persona' => 'Add Person',
        'anadir_articulo' => 'Add Item',
        'quien_pago' => 'Who paid the entire bill?',
        'me_deben_dinero' => 'Me (They owe me money)',
        'guardar_gasto' => 'Save Expense',
        'nombre_participante' => 'Participant name',
        'lista_contactos' => 'contact-list',
        
        // --- Expense History ---
        'historial_de_gastos' => 'Expense History',
        'revisa_todas' => 'Review all your accounts and mark who already paid you.',
        'genial_marcado' => 'Great! It has been marked as paid correctly. 🎉',
        'no_gastos_aun' => 'You don\'t have any expenses recorded yet. Go to "Split" to create one!',
        'pagado_por' => 'Paid by:',
        'mi_parte' => 'My part',
        'estado' => 'Status',
        'pagado' => 'Paid ✔️',
        'pendiente' => 'Pending',
        'recibido' => 'Received ✅',
        'confirmas_que_pago' => 'Do you confirm that ',
        'ya_pago_su_parte' => ' already paid their share?',
        
        // --- Statistics ---
        'tus_tendencias' => 'Your Financial Trends',
        'gastado_ultimo_mes' => 'Spent last month',
        'por_cobrar_me_deben' => 'To Collect (They owe me)',
        'por_pagar_debo' => 'To Pay (I owe)',
        'comparacion_mes_mes' => 'Month to Month Comparison',
        'gastos_por_categoria' => 'Expenses by Category',
        'total_gastado' => 'Total Spent ($)',
        
        // --- Fixed Expenses ---
        'mis_gastos_fijos' => 'My Fixed Expenses',
        'controla_recurrentes' => 'Control your monthly recurring payments',
        'nuevo_gasto_fijo' => 'New Fixed Expense',
        'titulo_label' => 'Title',
        'ej_netflix' => 'E.g: Netflix, Rent...',
        'monto_label' => 'Amount ($)',
        'dia_cobro' => 'Due date (1-31)',
        'dia_valor' => '15',
        'guardar_fijo' => 'Save Fixed Expense',
        'dia_badge' => 'Day ',
        'no_gastos_fijos' => 'You don\'t have any fixed expenses recorded.',
        'monto_fijo' => '$',
        
        // --- Contacts ---
        'mis_personas_frecuentes' => 'My Frequent People',
        'nombre_contacto' => 'Name of new contact...',
        'anadir_contacto' => 'Add',
        'seguro_eliminar' => 'Are you sure you want to delete this contact? Their expenses will remain in history.',
        'sigue_en_historial' => 'It will remain in history.',
        'me_debe' => 'They owe me',
        'le_debo' => 'I owe them',
        'cobrar' => 'Collect',
        'pagar' => 'Pay',
        'sin_movimientos' => 'No pending movements',
        
        // --- System Messages ---
        'accion_irreversible' => 'Are you sure? This action cannot be undone.',
        'bienvenido_vuelta' => 'Welcome back, ',
        'gasto_guardado' => 'The expense has been saved successfully.',
        'contacto_guardado' => 'Contact saved successfully.',
        'procesando' => 'Processing...',
        'error' => 'Error',
        'exito' => 'Success',
        'total_usuarios_registrados' => 'Total Registered Users',
        'monitor_eventos' => 'Event Monitor (NoSQL JSON)',
        'lectura_json_descripcion' => 'Direct reading from JSON file without using the relational database.',
        'fecha_hora' => 'Date and Time',
        'id_usuario' => 'User ID',
        'accion' => 'Action',
        'detalle_dinamico' => 'Dynamic Detail (JSON)',
        'no_registros_actividad' => 'No activity records yet.',
        'calculos' => 'Calculations',
        'divisor_con_propina' => 'Tip Splitter',
        'monto_total_ticket' => 'Total Ticket Amount',
        'de_propina' => 'Tip %',
        'entre_cuantos' => 'How many people?',
        'cada_uno_paga' => 'Everyone pays:',
        'detalle_propina' => '(Includes $0.00 total tip)',
        'notificaciones' => 'Notifications',
    ]
];
?>